name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        id: generate_snake
        uses: Platane/snk@v2
        with:
          github_user_name: AhmedAsim-69
          outputs: dist/snake.svg

      - name: Debug Information
        run: echo "Outputs: ${{ steps.generate_snake.outputs }}"
        
      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
